# config.yaml
pic_size: [600, 600]
pic_width: 600
pic_height: 600
pixel_size: 10

colors_palette:
  White:      [255, 255, 255]
  Black:      [0, 0, 0]
  Green:      [0, 128, 0]
  Blue:       [0, 0, 255]
  Red:        [255, 0, 0]
  Cyan:       [0, 255, 255]
  IndianRed:  [205, 92, 92]
  DeepPink:   [255, 20, 147]
  Gray:       [128, 128, 128]
  Yellow:     [255, 255, 0]
  Purple:     [128, 0, 128]

custom_colors_small:
  White:      [255, 255, 25]
  Black:      [0, 0, 0]
  Green:      [0, 128, 0]
  Blue:       [0, 0, 255]
  Red:        [255, 0, 0]
  Cyan:       [0, 255, 255]
  IndianRed:  [205, 92, 92]
  DeepPink:   [255, 20, 147]
  Gray:       [128, 128, 12]
  Yellow:     [255, 255, 0]
  Purple:     [128, 0, 128]

custom_colors_large:
  White:                       [255, 255, 255]
  Black:                       [0, 0, 0]
  Green:                       [0, 128, 0]
  Blue:                        [0, 0, 255]
  Red:                         [255, 0, 0]
  Cyan:                        [0, 255, 255]
  IndianRed:                   [205, 92, 92]
  DeepPink:                    [255, 20, 147]
  Gray:                        [128, 128, 12]
  Yellow:                      [255, 255, 0]
  Purple:                      [128, 0, 128]
  Maroon:                      [128, 0, 0]
  Lime:                        [0, 255, 0]
  Silver:                      [192, 192, 192]
  DarkRed:                     [139, 0, 0]
  Brown:                       [165, 42, 42]
  Firebrick:                   [178, 34, 34]
  Tomato:                      [255, 99, 71]
  Coral:                       [255, 127, 80]
  LightCoral:                  [240, 128, 128]
  DarkSalmon:                  [233, 150, 122]
  Salmon:                      [250, 128, 114]
  LightSalmon:                 [255, 160, 122]
  OrangeRed:                   [255, 69, 0]
  DarkOrange:                  [255, 140, 0]
  Orange:                      [255, 165, 0]
  Gold:                        [255, 215, 0]
  DarkGoldenRod:               [184, 134, 11]
  GoldenRod:                   [218, 165, 32]
  PaleGoldenRod:               [238, 232, 170]
  DarkKhaki:                   [189, 183, 107]
  Khaki:                       [240, 230, 140]
  Olive:                       [128, 128, 0]
  YellowGreen:                 [154, 205, 50]
  DarkOliveGreen:              [85, 107, 47]
  OliveDrab:                   [107, 142, 35]
  LawnGreen:                   [124, 252, 0]
  Chartreuse:                  [127, 255, 0]
  GreenYellow:                 [173, 255, 47]
  DarkGreen:                   [0, 100, 0]
  ForestGreen:                 [34, 139, 34]
  LimeGreen:                   [50, 205, 50]
  LightGreen:                  [144, 238, 144]
  PaleGreen:                   [152, 251, 152]
  DarkSeaGreen:                [143, 188, 143]
  MediumSpringGreen:           [0, 250, 154]
  SpringGreen:                 [0, 255, 127]
  SeaGreen:                    [46, 139, 87]
  MediumAquaMarine:            [102, 205, 170]
  MediumSeaGreen:              [60, 179, 113]
  LightSeaGreen:               [32, 178, 170]
  DarkSlateGray:               [47, 79, 79]
  DarkCyan:                    [0, 139, 139]
  Aqua:                        [0, 255, 255]
  LightCyan:                   [224, 255, 255]
  DarkTurquoise:               [0, 206, 209]
  Turquoise:                   [64, 224, 208]
  MediumTurquoise:             [72, 209, 204]
  PaleTurquoise:               [175, 238, 238]
  AquaMarine:                  [127, 255, 212]
  PowderBlue:                  [176, 224, 230]
  CadetBlue:                   [95, 158, 160]
  SteelBlue:                   [70, 130, 180]
  CornFlowerBlue:              [100, 149, 237]
  DeepSkyBlue:                 [0, 191, 255]
  DodgerBlue:                  [30, 144, 255]
  LightBlue:                   [173, 216, 230]
  SkyBlue:                     [135, 206, 235]
  LightSkyBlue:                [135, 206, 250]
  MidnightBlue:                [25, 25, 112]
  Navy:                        [0, 0, 128]
  DarkBlue:                    [0, 0, 139]
  MediumBlue:                  [0, 0, 205]
  RoyalBlue:                   [65, 105, 225]
  BlueViolet:                  [138, 43, 226]
  Indigo:                      [75, 0, 130]
  DarkSlateBlue:               [72, 61, 139]
  SlateBlue:                   [106, 90, 205]
  MediumSlateBlue:             [123, 104, 238]
  MediumPurple:                [147, 112, 219]
  DarkMagenta:                 [139, 0, 139]
  DarkViolet:                  [148, 0, 211]
  DarkOrchid:                  [153, 50, 204]
  MediumOrchid:                [186, 85, 211]
  Thistle:                     [216, 191, 216]
  Plum:                        [221, 160, 221]
  Violet:                      [238, 130, 238]
  Orchid:                      [218, 112, 214]